#! usr/bin/env lua
-- generate_core_cmakelists.lua

local generate_core_cmakelists = {}

local path_analyse = require("backend.scripts.base.path_analyse")

---生成核心区域cmakelist
---@param project_name_arg string
---@param project_version_arg string
---@param root_path_arg string
function generate_core_cmakelists.generateCore(project_name_arg, project_version_arg, root_path_arg)
    io.write("[Lua] Generating core CMakeLists.txt files...\n")
    io.flush()
    local file,err = io.open(path_analyse.join(root_path_arg, "core", "CMakeLists.txt"), "w")
    if not file then    
        io.write("[Lua] Error opening file: " .. err .. "\n")
        io.flush()
        return
    end
    file:write(string.format([[
# ========================================================
# AUTOMATICALLY GENERATED BY LUA - DO NOT EDIT MANUALLY
# Generated on: %s
# ========================================================

# 依赖处理
find_package(Threads REQUIRED)
# find_package(SQLite3 REQUIRED)

# find_package(protobuf CONFIG QUIET)
# if(NOT protobuf_FOUND)
# 	find_package(Protobuf CONFIG REQUIRED)
# endif()
# find_package(gRPC CONFIG REQUIRED)




file(GLOB_RECURSE BACKEND_SOURCES CONFIGURE_DEPENDS
	${CMAKE_CURRENT_SOURCE_DIR}/registrar/*.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/repository/*.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/route/*.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/task_manager/*.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/transport/*.cpp
	# ${CMAKE_CURRENT_SOURCE_DIR}/generated/*.cc
)

add_library(
    core STATIC
    ${BACKEND_SOURCES}
)

target_include_directories(
    core PRIVATE
	${CMAKE_CURRENT_SOURCE_DIR}
	${CMAKE_CURRENT_SOURCE_DIR}/registrar
	${CMAKE_CURRENT_SOURCE_DIR}/repository
	${CMAKE_CURRENT_SOURCE_DIR}/route
	${CMAKE_CURRENT_SOURCE_DIR}/task_manager
	${CMAKE_CURRENT_SOURCE_DIR}/transport
)

target_link_libraries(
    core 
    PRIVATE
	Threads::Threads
	httplib
    nlohmann_json
    # gRPC::grpc++
	# protobuf::libprotobuf
	# SQLite3::SQLite3

)

target_link_libraries(${project_name} PRIVATE core)

# 编译选项设置
set(COMPILE_OPTIONS_TARGETS ${project_name} core)

function(set_compile_options target_name)
    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /utf-8)
    else()
        target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
endfunction()


foreach(target_name IN LISTS COMPILE_OPTIONS_TARGETS)
    set_compile_options(${target_name})
endforeach()

# ========================================================
# Your custom core-specific CMake configurations go here
# ========================================================
]],
        os.date("%Y-%m-%d %H:%M:%S")
    ))
    file:close()
    io.write("[Lua] core CMakeLists.txt files generated successfully.\n")
    io.flush()
end

return generate_core_cmakelists