#! usr/bin/env lua
-- generate_domain_cmakelists.lua

local generate_domain_cmakelists = {}

local path_analyse = require("backend.scripts.base.path_analyse")

---生成用户侧cmakelist
---@param project_name_arg string
---@param project_version_arg string
---@param root_path_arg string
function generate_domain_cmakelists.generateDomain(project_name_arg, project_version_arg, root_path_arg)
    io.write("[Lua] Generating domain CMakeLists.txt files...\n")
    io.flush()
    local file,err = io.open(path_analyse.join(root_path_arg, "domain", "CMakeLists.txt"), "w")
    if not file then
        io.write("[Lua] Error opening file: " .. err .. "\n")
        io.flush()
        return
    end
    file:write(string.format([[
# ========================================================
# AUTOMATICALLY GENERATED BY LUA - DO NOT EDIT MANUALLY
# Generated on: %s
# ========================================================
file(GLOB_RECURSE DOMAIN_HANDLER_SOURCES CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_SOURCE_DIR}/handlers/*.cpp
)

target_sources(${project_name} PRIVATE
    ${DOMAIN_HANDLER_SOURCES}
)
# ========================================================
# Your custom domain-specific CMake configurations go here
# ========================================================
]],
        os.date("%Y-%m-%d %H:%M:%S")
    ))
    file:close()
    io.write("[Lua] domain CMakeLists.txt files generated successfully.\n")
    io.flush()
end

return generate_domain_cmakelists