#! /usr/bin/env lua
-- generate_third_party_config.lua
print("[Lua] Analyzing multi-dimensional component registry...")

-- 1. 模拟复杂的结构化组件数据（可以包含多维数组、条件开关等）
local third_parties = {
  {
    name = "httplib",
    repoLink = "https://github.com/yhirose/cpp-httplib.git",
    version = "v0.45.0",
  },
  {
    name = "nlohmann_json",
    repoLink = "https://github.com/nlohmann/json.git",
    version = "v3.12.0"
  }
}

-- 2. 打开即将生成的临时 cmake 文件
local output_path = arg[1]
local file, err = io.open(output_path, "w")
if not file then error("Failed to write file: " .. tostring(err)) end

-- 3. 写入自动化生成的头部警告（防止别人手动误改）
file:write(string.format([[
# ========================================================
# AUTOMATICALLY GENERATED BY LUA - DO NOT EDIT MANUALLY
# Generated on: %s
# ========================================================
]],
  os.date("%Y-%m-%d %H:%M:%S")
))

file:flush()

for _, third_party in ipairs(third_parties) do
  print([[
[Lua] Generating target configuration for: ]] .. third_party.name
  )

  file:write(string.format([[
#Target: %s
handle_third_party(
    %s    
    %s    
    %s
)

]],
    third_party.name,
    third_party.name,
    third_party.repoLink,
    third_party.version
  ))
end

  file:flush()

file:close()

print([[
[Lua] Code generation complete: ]] .. output_path)