#! usr/bin/env lua
-- generate_domain_cmakelists.lua

local generate_domain_cmakelists = {}

---生成用户侧cmakelist
---@param project_name_arg string
---@param project_version_arg string
---@param root_path_arg string
function generate_domain_cmakelists.generateDomain(project_name_arg, project_version_arg, root_path_arg)
    io:write("[Lua] Generating domain CMakeLists.txt files...\n")
    io:flush()
    local file,err = io.open(root_path_arg .. "/domain/CMakeLists.txt", "w")
    if not file then
        io:write("[Lua] Error opening file: " .. err .. "\n")
        io:flush()
        return
    end
    file:write(string.format([[
# ========================================================
# AUTOMATICALLY GENERATED BY LUA - DO NOT EDIT MANUALLY
# Generated on: %s
# ========================================================

# ========================================================
# Your custom domain-specific CMake configurations go here
# ========================================================
]],
        os.date("%Y-%m-%d %H:%M:%S")
    ))
    file:close()
    io:write("[Lua] domain CMakeLists.txt files generated successfully.\n")
    io:flush()
end

return generate_domain_cmakelists