#pragma once
#ifndef TASK_MODEL_H
#define TASK_MODEL_H

#include <vector>
#include <cstdint>
#include <string>

#include "../route/RouteKey.h"

namespace backend_core
{
    namespace v1
    {
        struct ContentItem
        {
            std::string uuid;
            std::string title;
            std::string body;
            std::int64_t updatedAt = 0;
            std::int64_t version = 0;
        };

        // TaskRequest is the request sent by the client to create a task. 
        //  The taskId is generated by the client, and it should be unique. 
        // The route is used to identify which func the task belongs to, and the content is the input of the func.
        struct TaskRequest
        {
            std::string taskId;
            RouteKey route;
            ContentItem content;
            std::int64_t retryCount = 0;
        };

        struct TaskEnvelope
        {
            std::string taskId;
            RouteKey route;
            bool success = false;
            std::string message;
            std::int64_t processedAt = 0;

            bool hasItem = false;
            ContentItem item;
            std::vector<ContentItem> items;
        };
    }
}



#endif // TASK_MODEL_H
