# ========================================================
# AUTOMATICALLY GENERATED BY LUA - DO NOT EDIT MANUALLY
# Generated on: 2026-05-22 00:18:47
# ========================================================
#Target: httplib
handle_third_party(
    httplib    
    https://github.com/yhirose/cpp-httplib.git    
    v0.45.0
)

#Target: nlohmann_json
handle_third_party(
    nlohmann_json    
    https://github.com/nlohmann/json.git    
    v3.12.0
)

